#!/usr/bin/env bash
# Generate the published docs/ site from web/.
#
# web/ is the single source of truth for the browser runtime and its smoke
# tests. docs/ is what GitHub Pages serves, and is web/ plus the tracked demo
# packs. Keeping two hand-maintained copies of a 962-line reader guaranteed
# silent drift, so docs/ is now generated and CI fails if it is stale.
#
# Demo packs are NOT copied here: docs/*.annpack and docs/packs/*.annpack are
# tracked publishing artifacts regenerated by scripts/build-demo-packs.sh.
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/.." && pwd)
cd "$ROOT"

mkdir -p docs/pkg
# Shared runtime and smoke sources.
for file in web/*.js web/*.mjs web/*.html web/*.py web/*.sh; do
  [ -e "$file" ] || continue
  cp "$file" "docs/$(basename "$file")"
done
# wasm-bindgen output.
rm -rf docs/pkg
cp -R web/pkg docs/pkg

echo "docs/ synchronized from web/"
